spring:
  profiles:
    active: dev

logging:
  level:
    root: info
    com.app.listing.ebay: trace

app:
  clientId: MohamedH-listinga-SBX-eccf1173b-6aa623cf
  secret: SBX-ccf1173baade-bfbf-460d-a7c6-e009
  redirectUri: Mohamed_Hassan-MohamedH-listin-mprlppm


ebay:
  config:
    base.url:
      inventory: https://api.sandbox.ebay.com/sell/inventory/v1/
      account: https://api.sandbox.ebay.com/sell/account/v1/
      fulfillment: https://api.sandbox.ebay.com/sell/fulfillment/v1/
      compliance: https://api.sandbox.ebay.com/sell/compliance/v1/
      analytics: https://api.sandbox.ebay.com/sell/analytics/v1/
      logistics: https://api.sandbox.ebay.com/sell/logistics/v1/

    scope:
      sell.inventory: https://rest.ebay.com/oauth/api_scope/sell.inventory
    grantType:
      authorizationCode: authorization_code
      clientCredentials: client_credentials

  auth:
    url:
      authorize: https://auth.sandbox.ebay.com/oauth2/authorize
      generateToken: https://api.sandbox.ebay.com/identity/v1/oauth2/token
